<div class="form-grid">
    <div class="form-group"><label class="form-label" for="name">Full name</label><input class="form-control" id="name" name="name" value="{{ old('name', $user->name ?? '') }}" required></div>
    <div class="form-group"><label class="form-label" for="email">Email address</label><input class="form-control" id="email" name="email" type="email" value="{{ old('email', $user->email ?? '') }}" required></div>
    <div class="form-group"><label class="form-label" for="role">Role</label><select class="form-select" id="role" name="role" required @disabled(isset($user) && auth()->user()->is($user))>@foreach(['admin', 'manager', 'member'] as $role)<option value="{{ $role }}" @selected(old('role', $user->role ?? 'member') === $role)>{{ ucfirst($role) }}</option>@endforeach</select>@if(isset($user) && auth()->user()->is($user))<input name="role" type="hidden" value="admin">@endif</div>
    <div class="form-group"><label class="form-label" for="is_active">Account status</label><select class="form-select" id="is_active" name="is_active" @disabled(isset($user) && auth()->user()->is($user))><option value="1" @selected((string) old('is_active', $user->is_active ?? 1) === '1')>Active</option><option value="0" @selected((string) old('is_active', $user->is_active ?? 1) === '0')>Disabled</option></select>@if(isset($user) && auth()->user()->is($user))<input name="is_active" type="hidden" value="1">@endif</div>
    <div class="form-group"><label class="form-label" for="password">Password</label><input class="form-control" id="password" name="password" type="password" {{ isset($user) ? '' : 'required' }}><span class="form-help">{{ isset($user) ? 'Leave blank to keep the current password.' : 'Minimum 8 characters.' }}</span></div>
    <div class="form-group"><label class="form-label" for="password_confirmation">Confirm password</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" {{ isset($user) ? '' : 'required' }}></div>
</div>
<div class="form-actions"><a class="btn btn-secondary" href="{{ route('users.index') }}">Cancel</a><button class="btn btn-primary" type="submit">{{ $submitLabel }}</button></div>

