<div class="form-grid">
    <div class="form-group full"><label class="form-label" for="title">Task title</label><input class="form-control" id="title" name="title" value="{{ old('title', $task->title ?? '') }}" maxlength="160" required></div>
    <div class="form-group"><label class="form-label" for="project_id">Project</label><select class="form-select" id="project_id" name="project_id" required><option value="">Select a project</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((string) old('project_id', $task->project_id ?? $selectedProject ?? '') === (string) $project->id)>{{ $project->name }}</option>@endforeach</select></div>
    <div class="form-group"><label class="form-label" for="assigned_to">Assignee</label><select class="form-select" id="assigned_to" name="assigned_to"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) old('assigned_to', $task->assigned_to ?? '') === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div>
    <div class="form-group"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status" required>@foreach(['todo' => 'To do', 'in_progress' => 'In progress', 'review' => 'Review', 'completed' => 'Completed'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $task->status ?? 'todo') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="form-group"><label class="form-label" for="priority">Priority</label><select class="form-select" id="priority" name="priority" required>@foreach(['low', 'medium', 'high'] as $priority)<option value="{{ $priority }}" @selected(old('priority', $task->priority ?? 'medium') === $priority)>{{ ucfirst($priority) }}</option>@endforeach</select></div>
    <div class="form-group"><label class="form-label" for="due_at">Due date</label><input class="form-control" id="due_at" name="due_at" type="date" value="{{ old('due_at', isset($task) ? $task->due_at?->format('Y-m-d') : '') }}"></div>
    <div class="form-group full"><label class="form-label" for="description">Description</label><textarea class="form-control" id="description" name="description" maxlength="3000">{{ old('description', $task->description ?? '') }}</textarea></div>
</div>
<div class="form-actions"><a class="btn btn-secondary" href="{{ route('tasks.index') }}">Cancel</a><button class="btn btn-primary" type="submit">{{ $submitLabel }}</button></div>

